### ISSUE TITLE
Error saat run di Linux

### ISSUE THREAD

**Issue by Mysteriza** [Dra-Ganzz/Spm-Whatsapp#2]
Muncul error berikut:
 ✓ Apikey Valid >_<
[Errno 2] No such file or directory: '/data/data/com.termux/.token.json'

Padahal saya mengikuti langkah install untuk Linux. Bagaimana ini bang?

**Comment by Dra-Ganzz** [comment]
Tar di update ya sabar aja paling maleman

Pada Sel, 10 Des 2024 16.53, Rifqi Fachriza S ***@***.***>
menulis:

**Comment by Mysteriza** [comment]
Masih ada error bang, wkwkw.
[Errno 2] No such file or directory: '/Data/.token.json'

**Comment by Mysteriza** [comment]
Anehnya, penambahan file .token.json ga mempengaruhi hasil, program tetep ga bisa membaca kalo file itu udah ada di direktori Data.

**Comment by Dra-Ganzz** [comment]
Hey tolong chat lewat telegram saja t.me/vindraganzz

Pada Sel, 10 Des 2024 22.56, Rifqi Fachriza S ***@***.***>
menulis:
